server:
  port: 9090
    
company:
  companyname: RevatureIndiaPvtLtd
  companylocation: bangalore
  companyaddress: electroniccity
  
management:
  endpoints:
    enabled-by-default: true 
  health:
    enabled: true